
spring:
  application:
    name: wallet
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/ddl_jpa_creation.sql
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: milad
    password: root
    hikari:
      poolName: wallet-dev
      auto-commit: false
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 150000
      connection-timeout: 15000
      max-lifetime: 18000000