server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: wallet
  profiles:
    active: #spring.profiles.active#
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        enable_lazy_load_no_trans: true
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/ddl_jpa_creation.sql
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always